/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GlossaryIndexRouteImport } from './routes/glossary/index'
import { Route as CategoriaSlugRouteImport } from './routes/categoria/$slug'
import { Route as ArtigoSlugRouteImport } from './routes/artigo/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryIndexRoute = GlossaryIndexRouteImport.update({
  id: '/glossary/',
  path: '/glossary/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtigoSlugRoute = ArtigoSlugRouteImport.update({
  id: '/artigo/$slug',
  path: '/artigo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artigo/$slug': typeof ArtigoSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/glossary/': typeof GlossaryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artigo/$slug': typeof ArtigoSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/glossary': typeof GlossaryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artigo/$slug': typeof ArtigoSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/glossary/': typeof GlossaryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/artigo/$slug' | '/categoria/$slug' | '/glossary/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/artigo/$slug' | '/categoria/$slug' | '/glossary'
  id: '__root__' | '/' | '/artigo/$slug' | '/categoria/$slug' | '/glossary/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtigoSlugRoute: typeof ArtigoSlugRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  GlossaryIndexRoute: typeof GlossaryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary/': {
      id: '/glossary/'
      path: '/glossary'
      fullPath: '/glossary/'
      preLoaderRoute: typeof GlossaryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artigo/$slug': {
      id: '/artigo/$slug'
      path: '/artigo/$slug'
      fullPath: '/artigo/$slug'
      preLoaderRoute: typeof ArtigoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtigoSlugRoute: ArtigoSlugRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  GlossaryIndexRoute: GlossaryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
