/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GlossaryIndexRouteImport } from './routes/glossary/index'
import { Route as GlossaryWhatIsTermRouteImport } from './routes/glossary/what-is-$term'
import { Route as CategoriaSlugRouteImport } from './routes/categoria/$slug'
import { Route as ArtigoSlugRouteImport } from './routes/artigo/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryIndexRoute = GlossaryIndexRouteImport.update({
  id: '/glossary/',
  path: '/glossary/',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryWhatIsTermRoute = GlossaryWhatIsTermRouteImport.update({
  id: '/glossary/what-is-$term',
  path: '/glossary/what-is-$term',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtigoSlugRoute = ArtigoSlugRouteImport.update({
  id: '/artigo/$slug',
  path: '/artigo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artigo/$slug': typeof ArtigoSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/glossary/what-is-$term': typeof GlossaryWhatIsTermRoute
  '/glossary/': typeof GlossaryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artigo/$slug': typeof ArtigoSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/glossary/what-is-$term': typeof GlossaryWhatIsTermRoute
  '/glossary': typeof GlossaryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artigo/$slug': typeof ArtigoSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/glossary/what-is-$term': typeof GlossaryWhatIsTermRoute
  '/glossary/': typeof GlossaryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artigo/$slug'
    | '/categoria/$slug'
    | '/glossary/what-is-$term'
    | '/glossary/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artigo/$slug'
    | '/categoria/$slug'
    | '/glossary/what-is-$term'
    | '/glossary'
  id:
    | '__root__'
    | '/'
    | '/artigo/$slug'
    | '/categoria/$slug'
    | '/glossary/what-is-$term'
    | '/glossary/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtigoSlugRoute: typeof ArtigoSlugRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  GlossaryWhatIsTermRoute: typeof GlossaryWhatIsTermRoute
  GlossaryIndexRoute: typeof GlossaryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary/': {
      id: '/glossary/'
      path: '/glossary'
      fullPath: '/glossary/'
      preLoaderRoute: typeof GlossaryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary/what-is-$term': {
      id: '/glossary/what-is-$term'
      path: '/glossary/what-is-$term'
      fullPath: '/glossary/what-is-$term'
      preLoaderRoute: typeof GlossaryWhatIsTermRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artigo/$slug': {
      id: '/artigo/$slug'
      path: '/artigo/$slug'
      fullPath: '/artigo/$slug'
      preLoaderRoute: typeof ArtigoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtigoSlugRoute: ArtigoSlugRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  GlossaryWhatIsTermRoute: GlossaryWhatIsTermRoute,
  GlossaryIndexRoute: GlossaryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
